name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 

      # Install dependencies from the pyproject.toml using dev and test extras
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,test]

      # Run Ruff (linting)
      - name: Run Ruff
        run: ruff check .

      # Run mypy (type checking)
      - name: Run mypy
        run: mypy .

      # Run isort (checking imports sorting)
      - name: Run isort
        run: isort .

      # Uncomment when tests are added
      ## Run Pytest (tests)
      # - name: Run Pytest
      #   run: pytest
