name: CI

on: push
  # pull_request:
  #   branches:
  #     - main

jobs:
  format_and_lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 

      # Install dependencies from the pyproject.toml using dev and test extras
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Run Ruff (linting)
      - name: Run Ruff
        run: ruff check .

      # Run mypy (type checking)
      - name: Run mypy
        run: mypy .

      # Run isort (checking imports sorting)
      - name: Run isort
        run: isort .
  
  test:
    runs-on: ubuntu-latest
    needs: format_and_lint
    steps:
            # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 

      # Install dependencies from the pyproject.toml using dev and test extras
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      # Run Pytest (tests)
      - name: Run Pytest
        run: pytest

  # Bump version number
  bump_version:
    runs-on: ubuntu-latest

    needs: [format_and_lint, test]
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PAT }}


